awsSns:
  region: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  accessKeyId: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  secretAccessKey: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  applicationArn: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  roomTopicNamePrefix:
