version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: /go/src/github.com/swagchat/chat-api
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/chat-api
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/chat-api | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=chat-api -t chat-api .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/chat-api chat-api
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/chat-api
      - run:
          name: "run docker build"
          command: |
            docker build -t swagchat/chat-api .
