#################################################
#             Chat API settings                 #
#################################################
httpPort: 8101
profiling: false
errorLogging: true
demoPage: true

#################### Logging ####################
logging:
  level: development

#################### Storage ####################
storage:
  provider: local
  baseurl: http://localhost:8101/v0/assets
  path: data/assets

#################### Datastore ##################
datastore:
  provider: sqlite
  sqlitePath: /tmp/swagchat.db
