gcpSql:
  projectId: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  sqlInstanceId: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  user: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  password: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  database: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  masterHost: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  masterPort: IT_IS_RECOMMENDED_TO_SET_BY_ENVIRONMENT_VARIABLE_OR_RUNTIME_PARAMETER
  maxIdleConnection: 10
  maxOpenConnection: 10
  useSSL: off
  serverCaPath:
  clientCertPath:
  clientKeyPath:
